package wowup

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"golang.org/x/sys/unix"
)

func artifactBytes() []byte {
	b := make([]byte, 256)
	copy(b, []byte("\x7fELF\x02\x01\x01\x00AI\x02"))
	binary.LittleEndian.PutUint16(b[18:], 62)
	binary.LittleEndian.PutUint64(b[40:], 64)
	binary.LittleEndian.PutUint16(b[58:], 64)
	binary.LittleEndian.PutUint16(b[60:], 1)
	copy(b[128:], "hsqs")
	binary.LittleEndian.PutUint16(b[156:], 4)
	binary.LittleEndian.PutUint64(b[168:], 96)
	return b
}

type fixture struct {
	e                      *Installer
	root, artifact, digest string
}

func setup(t *testing.T) fixture {
	t.Helper()
	root := t.TempDir()
	e := New()
	e.fixtureRoot = root
	e.uid, e.gid = uint32(os.Getuid()), uint32(os.Getgid())
	e.app = filepath.Join(root, "opt/wowup-cf")
	e.removing = filepath.Join(root, "opt/.nimbus-wowup-cf-removing")
	e.journal = filepath.Join(root, "opt/.nimbus-wowup-cf-removal.json")
	e.links = []link{{filepath.Join(root, "usr/local/bin/wowup-cf"), filepath.Join(e.app, "launcher")}, {filepath.Join(root, "usr/local/share/applications/wowup-cf.desktop"), filepath.Join(e.app, "wowup-cf.desktop")}}
	if err := os.MkdirAll(filepath.Dir(e.app), 0o755); err != nil {
		t.Fatal(err)
	}
	e.extract = func(_ context.Context, _ string, dest string) error {
		if err := os.Mkdir(dest, 0o755); err != nil {
			return err
		}
		if err := writeFile(filepath.Join(dest, "AppRun"), []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
			return err
		}
		return writeFile(filepath.Join(dest, "payload"), []byte("application payload"), 0o644)
	}
	path := filepath.Join(root, "official.AppImage")
	data := artifactBytes()
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(data)
	return fixture{e, root, path, hex.EncodeToString(sum[:])}
}
func (f fixture) install(t *testing.T, version string) Status {
	t.Helper()
	s, err := f.e.Apply(t.Context(), f.artifact, f.digest, version)
	if err != nil {
		t.Fatal(err)
	}
	return s
}
func TestLifecycle(t *testing.T) {
	f := setup(t)
	s, err := f.e.Status()
	if err != nil || s.Installed {
		t.Fatalf("absent: %+v %v", s, err)
	}
	if !f.install(t, "2.23.1").Integrated {
		t.Fatal("not integrated")
	}
	if err := os.Remove(f.e.links[0].path); err != nil {
		t.Fatal(err)
	}
	s, err = f.e.Status()
	if err != nil || s.Integrated || !s.Verified {
		t.Fatalf("missing link: %+v %v", s, err)
	}
	if !f.install(t, "2.23.1").Integrated {
		t.Fatal("repair failed")
	}
	if f.install(t, "2.23.2").Version != "2.23.2" {
		t.Fatal("update failed")
	}
	before, _ := os.ReadFile(filepath.Join(f.e.app, "receipt.json"))
	if _, err := f.e.Apply(t.Context(), f.artifact, f.digest, "2.23.1"); err == nil {
		t.Fatal("downgrade accepted")
	}
	after, _ := os.ReadFile(filepath.Join(f.e.app, "receipt.json"))
	if !bytes.Equal(before, after) {
		t.Fatal("downgrade changed receipt")
	}
	personal := filepath.Join(f.root, "user-data")
	if err := os.WriteFile(personal, []byte("preserve"), 0o600); err != nil {
		t.Fatal(err)
	}
	s, err = f.e.Uninstall(t.Context())
	if err != nil || s.Installed {
		t.Fatalf("remove: %+v %v", s, err)
	}
	if _, err := os.Stat(personal); err != nil {
		t.Fatal("user data removed")
	}
	for _, link := range f.e.links {
		if exists(link.path) {
			t.Fatal("integration remains")
		}
		if _, err := os.Stat(filepath.Dir(link.path)); err != nil {
			t.Fatal(err)
		}
	}
}
func TestPythonReceiptCompatibility(t *testing.T) {
	f := setup(t)
	f.install(t, "2.23.1")
	data, err := os.ReadFile("testdata/receipt-v1.json")
	if err != nil {
		t.Fatal(err)
	}
	// The committed fixture was generated by the original Python installer.
	var r Receipt
	if err := json.Unmarshal(data, &r); err != nil {
		t.Fatal(err)
	}
	// Match the original Python ELF fixture, including unused superblock fields.
	legacy := artifactBytes()
	binary.LittleEndian.PutUint32(legacy[132:], 1)
	binary.LittleEndian.PutUint32(legacy[140:], 131072)
	binary.LittleEndian.PutUint16(legacy[148:], 1)
	binary.LittleEndian.PutUint16(legacy[150:], 17)
	binary.LittleEndian.PutUint16(legacy[154:], 1)
	if err := os.WriteFile(filepath.Join(f.e.app, "WowUp-CF.AppImage"), legacy, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writeFile(filepath.Join(f.e.app, "receipt.json"), data, 0o644); err != nil {
		t.Fatal(err)
	}
	status, err := f.e.Status()
	if err != nil || !status.Verified {
		t.Fatalf("legacy receipt: %+v %v", status, err)
	}
	if _, err := f.e.Uninstall(t.Context()); err != nil {
		t.Fatal(err)
	}
}
func TestForeignAndModifiedStateBlocksMutation(t *testing.T) {
	for _, kind := range []string{"unknown", "changed", "privileged-receipt", "external-link", "foreign-launcher", "receipt-traversal"} {
		t.Run(kind, func(t *testing.T) {
			f := setup(t)
			f.install(t, "2.23.1")
			switch kind {
			case "unknown":
				os.WriteFile(filepath.Join(f.e.app, "personal"), []byte("keep"), 0o644)
			case "changed":
				os.WriteFile(filepath.Join(f.e.app, "app/payload"), []byte("changed"), 0o644)
			case "privileged-receipt":
				os.Chmod(filepath.Join(f.e.app, "receipt.json"), os.ModeSetuid|0o644)
			case "external-link":
				os.Symlink(f.artifact, filepath.Join(f.e.app, "outside"))
			case "foreign-launcher":
				os.Remove(f.e.links[0].path)
				os.Symlink("/unrelated", f.e.links[0].path)
			case "receipt-traversal":
				data, _ := os.ReadFile(filepath.Join(f.e.app, "receipt.json"))
				var r Receipt
				json.Unmarshal(data, &r)
				r.Entries["../victim"] = Entry{Type: "file", Mode: new(uint32(0o644)), SHA256: f.digest}
				data, _ = json.Marshal(r)
				writeFile(f.e.journal, data, 0o644)
			}
			if _, err := f.e.Uninstall(t.Context()); err == nil {
				t.Fatal("unsafe removal accepted")
			}
			if !exists(f.e.app) {
				t.Fatal("bundle deleted")
			}
		})
	}
}
func TestBadArtifactAndExtractionPreserveInstall(t *testing.T) {
	for _, kind := range []string{"digest", "symlink", "extract", "external-symlink", "parent-symlink"} {
		t.Run(kind, func(t *testing.T) {
			f := setup(t)
			path, digest := f.artifact, f.digest
			switch kind {
			case "digest":
				digest = strings.Repeat("0", 64)
			case "symlink":
				path = filepath.Join(f.root, "link")
				os.Symlink(f.artifact, path)
			case "extract":
				f.install(t, "2.23.1")
				f.e.extract = func(context.Context, string, string) error { return errors.New("injected extraction failure") }
			case "external-symlink":
				native := f.e.extract
				f.e.extract = func(ctx context.Context, a, d string) error {
					if err := native(ctx, a, d); err != nil {
						return err
					}
					return os.Symlink(f.artifact, filepath.Join(d, "external"))
				}
			case "parent-symlink":
				os.Mkdir(filepath.Join(f.root, "elsewhere"), 0o755)
				os.Symlink(filepath.Join(f.root, "elsewhere"), filepath.Join(f.root, "usr"))
			}
			if _, err := f.e.Apply(t.Context(), path, digest, "2.23.2"); err == nil {
				t.Fatal("invalid apply accepted")
			}
			if kind == "extract" {
				s, err := f.e.Status()
				if err != nil || s.Version != "2.23.1" || !s.Integrated {
					t.Fatalf("previous state: %+v %v", s, err)
				}
			} else if exists(f.e.app) {
				t.Fatal("invalid bundle published")
			}
		})
	}
}
func TestRestrictiveUmask(t *testing.T) {
	f := setup(t)
	old := unix.Umask(0o077)
	defer unix.Umask(old)
	f.install(t, "2.23.1")
	for _, link := range f.e.links {
		for parent := filepath.Dir(link.path); parent != f.root; parent = filepath.Dir(parent) {
			info, err := os.Stat(parent)
			if err != nil {
				t.Fatal(err)
			}
			if info.Mode().Perm() != 0o755 {
				t.Fatalf("%s: %o", parent, info.Mode().Perm())
			}
		}
	}
}
func TestIncompleteIntegrationRemoval(t *testing.T) {
	for index := range 2 {
		t.Run(fmtIndex(index), func(t *testing.T) {
			f := setup(t)
			failed := filepath.Dir(f.e.links[index].path)
			f.e.mkdir = func(path string, mode os.FileMode) error {
				if path == failed {
					return errors.New("injected mkdir failure")
				}
				return os.Mkdir(path, mode)
			}
			if _, err := f.e.Apply(t.Context(), f.artifact, f.digest, "2.23.1"); err == nil {
				t.Fatal("failure lost")
			}
			s, err := f.e.Status()
			if err != nil || !s.Verified || s.Integrated {
				t.Fatalf("partial state: %+v %v", s, err)
			}
			f.e.mkdir = os.Mkdir
			s, err = f.e.Uninstall(t.Context())
			if err != nil || s.Installed {
				t.Fatalf("remove partial: %+v %v", s, err)
			}
			if exists(failed) {
				t.Fatal("uninstall created directory")
			}
		})
	}
}
func fmtIndex(i int) string {
	if i == 0 {
		return "launcher"
	}
	return "desktop"
}
func TestRemovalRecovery(t *testing.T) {
	for _, kind := range []string{"integration", "sync", "payload", "final-directory"} {
		t.Run(kind, func(t *testing.T) {
			f := setup(t)
			f.install(t, "2.23.1")
			failed := f.e.links[1].path
			if kind == "payload" {
				failed = filepath.Join(f.e.removing, "app/payload")
			}
			if kind == "final-directory" {
				failed = f.e.removing
			}
			if kind == "sync" {
				f.e.syncDir = func(string) error { return errors.New("sync failed") }
			} else {
				f.e.remove = func(path string) error {
					if path == failed {
						return errors.New("remove failed")
					}
					return os.Remove(path)
				}
			}
			if _, err := f.e.Uninstall(t.Context()); err == nil {
				t.Fatal("failure lost")
			}
			f.e.syncDir = syncDirectory
			f.e.remove = os.Remove
			s, err := f.e.Status()
			if err != nil || !s.Verified {
				t.Fatalf("retry state: %+v %v", s, err)
			}
			if kind == "payload" || kind == "final-directory" {
				if !s.CleanupPending || !exists(f.e.journal) {
					t.Fatal("journal lost")
				}
				if _, err := f.e.Apply(t.Context(), f.artifact, f.digest, "2.23.1"); err == nil {
					t.Fatal("apply during removal accepted")
				}
			}
			s, err = f.e.Uninstall(t.Context())
			if err != nil || s.Installed || exists(f.e.journal) || exists(f.e.removing) {
				t.Fatalf("retry: %+v %v", s, err)
			}
		})
	}
}

type roundTrip func(*http.Request) (*http.Response, error)

func (f roundTrip) RoundTrip(r *http.Request) (*http.Response, error) { return f(r) }
func TestPrepareAndMetadataBoundaries(t *testing.T) {
	for _, kind := range []string{"valid", "draft", "prerelease", "foreign-url", "digest", "duplicate", "short", "excess", "bad-size"} {
		t.Run(kind, func(t *testing.T) {
			f := setup(t)
			asset := map[string]any{"name": "WowUp-CF-2.23.1.AppImage", "browser_download_url": sourceURL("2.23.1"), "digest": "sha256:" + f.digest, "size": 256}
			meta := map[string]any{"draft": false, "prerelease": false, "tag_name": "v2.23.1", "assets": []any{asset}}
			payload := artifactBytes()
			switch kind {
			case "draft":
				meta["draft"] = true
			case "prerelease":
				meta["prerelease"] = true
			case "foreign-url":
				asset["browser_download_url"] = "https://example.invalid/app"
			case "digest":
				asset["digest"] = "sha256:" + strings.Repeat("0", 64)
			case "duplicate":
				meta["assets"] = []any{asset, asset}
			case "short":
				payload = payload[:255]
			case "excess":
				payload = append(payload, 0)
			case "bad-size":
				asset["size"] = true
			}
			f.e.client.Transport = roundTrip(func(r *http.Request) (*http.Response, error) {
				data := payload
				if r.URL.Host == "api.github.com" {
					data, _ = json.Marshal(meta)
				}
				return &http.Response{StatusCode: 200, Body: io.NopCloser(bytes.NewReader(data)), Header: http.Header{}}, nil
			})
			a, err := f.e.Prepare(t.Context(), f.root, "")
			if kind == "valid" {
				if err != nil || a.SHA256 != f.digest || a.SchemaVersion != 1 || !exists(a.Path) {
					t.Fatalf("prepare: %+v %v", a, err)
				}
			} else {
				if err == nil {
					t.Fatal("invalid preparation accepted")
				}
				stages, _ := filepath.Glob(filepath.Join(f.root, "wowup-cf-*"))
				if len(stages) != 0 {
					t.Fatal("failed preparation left staging")
				}
			}
			if exists(f.e.app) {
				t.Fatal("prepare installed application")
			}
		})
	}
}
func TestOffsetsAndRedirects(t *testing.T) {
	f := setup(t)
	if offset, err := squashfsOffset(f.artifact); err != nil || offset != 128 {
		t.Fatalf("offset: %d %v", offset, err)
	}
	for _, raw := range []string{"http://github.com/WowUp/WowUp.CF/releases/download/a", "https://github.com.evil.invalid/WowUp/WowUp.CF/releases/download/a", "https://github.com/other/repo/releases/download/a"} {
		if officialURL(raw) {
			t.Fatal("unsafe URL accepted")
		}
	}
	if !officialURL(sourceURL("2.23.1")) {
		t.Fatal("official URL rejected")
	}
}

func TestCancellationWhileWaitingForLock(t *testing.T) {
	f := setup(t)
	held, err := f.e.lock(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	defer held.Close()
	ctx, cancel := context.WithTimeout(t.Context(), 100*time.Millisecond)
	defer cancel()
	lock, err := f.e.lock(ctx)
	if lock != nil {
		lock.Close()
	}
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("blocked lock ignored cancellation: %v", err)
	}
}
